### ISSUE TITLE
DMA Mode not working

### ISSUE THREAD

**Issue by cider101** [maudeve-it/ILI9XXX-XPT2046-STM32#2]
This is a great little library/driver - thx for your great work!

I'm having trouble to get the DMA mode to work. It "hangs" in the Displ_Transmit() function on line 77.   

while (!Displ_SpiAvailable) {};

It looks like there there is never a transfer-complete interrupt received - though both, the global SPI1 and DMA2 TX interrupts are enabled. I'v never worked with DMA before - do I need to configure something "special" except enabling the DMA TX ?
Btw: it works in "normal" Interrupt-Mode - just not in DMA mode....

**Comment by maudeve-it** [comment]
Hi cider101,
yes, it seems that DMA doesn't signal transfer-complete.
Which uC are you using?
Have you enabled SPI interrupt? ("SPIx global interrupt" enabled, on "NVIC settings", in the SPIx "Configuration" page)
That has to be enabled together with the SPIx_TX settings.
Let me know.

Bye

**Comment by cider101** [comment]
Thx for your quick response.
I'm using an SMT32F401 Weact Blackpill and yes,  both, SPI1_TX and SPI1 global interrupt are enabled...
As mentioned before, I haven't used DMA yet - so please forgive my ignorance. From the HAL code I understood, that the DMATransferCompleted-IRQ/Event ist routed by HAL from the DMA-IRQ-Handle to the to the SPI-IRQ-Handler which then will finally call the function HAL_SPI_TxCpltCallback() from your library - right ?

<img width="706" alt="image" src="https://user-images.githubusercontent.com/6802535/219748562-a8e579d7-c279-416d-aca2-8c182ea17f1c.png">

<img width="706" alt="image" src="https://user-images.githubusercontent.com/6802535/219749187-2c9327ab-de84-468b-973a-5c48aa251c9f.png">

**Comment by maudeve-it** [comment]
Hi Cider101
3 more questions:
- can you tell me the display you are using?
- can you tell me the configuration in z_displ_ILI9XXX.h?  I mean the values enabled in STEP1 to STEP6
- can you also show me lines in "main.c" between  /* USER CODE END SysInit */ and    /* USER CODE BEGIN 2 */
thet means the initialization sequence set by CubeMX?

Thank you

**Comment by cider101** [comment]
Good Morning Mauro

I'm using a [ILI9488 Display with an FT6236](https://www.aliexpress.com/item/1005005131909757.html?spm=a2g0o.productlist.main.1.6c677c45C2UAgC&algo_pvid=1c655dbc-0a6c-4725-acde-da3e0d072c3c&algo_exp_id=1c655dbc-0a6c-4725-acde-da3e0d072c3c-0&pdp_ext_f=%7B%22sku_id%22%3A%2212000031788323832%22%7D&pdp_npi=3%40dis%21USD%2110.66%2110.66%21%21%21%21%21%40211bf49716767133210281413d06ea%2112000031788323832%21sea%21CH%212291384215&curPageLogUid=9eMZ55INumDR)  touch controller

this is my configuration for the display in the z_displ_ILI9XXX.h
```
0. //#define DISPLAY_USING_TOUCHGFX

1. #define ILI9488_V1 (this display seems only to work with rgb666)

2. #define DISPL_SPI_PORT 	hspi1
    #define DISPL_SPI 		SPI1

3. #define DISPL_PRESCALER SPI_BAUDRATEPRESCALER_2     //prescaler assigned to display SPI port
   #define TOUCH_PRESCALER SPI_BAUDRATEPRESCALER_256	//prescaler assigned to touch device SPI port

4. //#define DISPLAY_SPI_POLLING_MODE
   //#define DISPLAY_SPI_INTERRUPT_MODE
    #define DISPLAY_SPI_DMA_MODE // (mixed: polling/DMA, see below)

5. //#define DISPLAY_DIMMING_MODE 

6. #define BUFLEVEL 12

```

and that's my main.c
  ```
MX_GPIO_Init();
  MX_SPI1_Init();
  MX_I2C1_Init();
  MX_TIM2_Init();
  MX_DMA_Init();

  /* USER CODE BEGIN 2 */
  Displ_Init(Displ_Orientat_0);
  Displ_CLS(BLUE);
  //Displ_BackLight('I');  			//currently hard-wired to 3v3 
  /* USER CODE END 2 */

  /* Infinite loop */
  /* USER CODE BEGIN WHILE */
  while (1)
  {
    /* USER CODE END WHILE */

    /* USER CODE BEGIN 3 */
	  Displ_PerfTest();
  }
  /* USER CODE END 3 */
```

thx again for your help! have a nice weekend
Marco

**Comment by maudeve-it** [comment]
Hi Cider101,
can you do these tests, changing the initialization order?

test 1:
MX_GPIO_Init();
MX_I2C1_Init();
MX_TIM2_Init();
MX_DMA_Init();
MX_SPI1_Init();

test 1:
MX_GPIO_Init();
MX_DMA_Init();
MX_I2C1_Init();
MX_TIM2_Init();
MX_SPI1_Init();
 
and let me know what happens?

**Comment by cider101** [comment]
It works!! thx a lot! And hell, what a performance-difference :) 

looks like the DMA needs to be initialized before the SPI is initialized. Seems this is a bug/issue with the Stm32CubeIDE since that code is generated by the IDE.

btw:did you ever figure out, what the difference between board version 1.0 and 2.0 is ? Maybe a different chip or firmware version/revision of the Ili9488 ?

thx again end enjoy the weekend
best regards
Marco

**Comment by maudeve-it** [comment]
Yes,
it seems (to me) that when you create a new project, CubeMX sets the right initialization order. Anytime.
But, if you start to "play" with your configuration: enabling DMA (and saving configuration), then disabling it, then changing its setup, many time... CubeMX can fall into a wrong sequence and it is not able to set it back to the right one.
You could set the initialization sequence inyo CubeMX -> Project Manager -> Advanced Settings but some sequences (including DMA) are protected (against your mistakes but not against CubeMX mistakes).

About your project: from now on, if you make any changing in configuration, CubeMX will set back the wrong order. The only way (I found) avoiding it is to create a new project

Bye
