### ISSUE TITLE
error: 'SPI_CR1_BR_Msk' undeclared

### ISSUE THREAD

**Issue by raf6410** [maudeve-it/ILI9XXX-XPT2046-STM32#3]
Hello,

I try to use your Library on my nucléo H723ZG.
 but i have this error :  
![image](https://user-images.githubusercontent.com/25167415/225337962-29a0e1aa-bb11-4c1b-89d7-8d7f3283fa22.png)

My setup is : nucléo H723ZG + ILI9488
                     MX CUBE IDE v1.11.2
                     TOUCHGFX 4.21.3
                     
![image](https://user-images.githubusercontent.com/25167415/225336855-3e555576-81af-4519-9d14-f3862b696f93.png)

Could you help me ?

**Comment by maudeve-it** [comment]
I see. H7 has a quite different SPI device structure so CMSIS instructions have to adapt to it, referring to the uC reference manual.
You should change that macro somehow like here:
#define SET_SPI_BAUDRATE(_P_SCALER_) 	DISPL_SPI->CFG1 &= (uint16_t) ~SPI_CFG1_MBR_Msk; \
									DISPL_SPI->CFG1 |= _P_SCALER_
but you have to verify and fix it in case of needs: I do not have an H7 in my drawers to check if it works

**Comment by raf6410** [comment]
hi,

Thanks for your response. Now my project compilation is OK and the display work.

**Comment by danad21** [comment]
Hello raf6410! Can I see you project folder files? I cannot make it work on my STM32H723. I would much appreciate it, thanks!
