### ISSUE TITLE
3.5'' LCD TFT ILI9488 V1.0 display with STM32F401RE

### ISSUE THREAD

**Issue by mokhlessezd** [maudeve-it/ILI9XXX-XPT2046-STM32#5]
i have a problem in the display .. i'm using STMCubeIDE and the code is correct and builded successfully ..but when i upload this code on my board the screen just light and not showing any display 
![355145815_222147344092283_4919969733011404584_n](https://github.com/maudeve-it/ILI9XXX-XPT2046-STM32/assets/126563374/e2949e0e-d96c-4431-84d3-2c5a1315abf8)
![Capture](https://github.com/maudeve-it/ILI9XXX-XPT2046-STM32/assets/126563374/c9b341fd-890b-4259-ab06-ff27a0494f8f)
by the way the screen is not damaged beacause i try to work with it with esp8266 and it works

**Comment by maudeve-it** [comment]
Actually the problem seems not related to dyisplay, not to the project or the library configuration but it is far before: it seems to be about st-link

**Comment by mokhlessezd** [comment]
Thank you very much sir ..ye helped me very much ! it works now
